name: iOS Build with Xcode 16

on:
  push:
    branches:
      - develop

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Set up Signing Credentials
        run: |
          security create-keychain -p "temp_password" temp.keychain
          security import ./certificate.p12 -k temp.keychain -P "123456" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "temp_password" temp.keychain
          security list-keychains -s temp.keychain
          security unlock-keychain -p "temp_password" temp.keychain
          security set-keychain-settings -lut 3600 temp.keychain

      - name: Set up Provisioning Profile from Project Folder
        run: |
          mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
          cp ./distribution.mobileprovision ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/
      
      # 5. Install Fastlane using Homebrew
      - name: Install Fastlane
        run: |
          brew install fastlane

      # 6. Run Fastlane lane for TestFlight upload
      - name: Run Fastlane Lane
        env:
          PROFILE: ¡°#YOUR_DISTRIBUTION_PROVISIONING_PROFILE_NAME#¡°
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        run: |
          fastlane beta --verbose
